name: CI/CD
     
on: 
  pull_request:
    branches: 
      - qa
    types:
      - opened
      - synchronize
    paths:
      - 'force-app/**'

jobs:
  before-deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0
