###########
# @title Salesforce Easy Checks - Templated Github Action
# @filename testpipeline.yaml
# @description Tests the checks pipeline and its core functions
# @author Benjamin Ngo
###########


name: Test Pipeline Check

on: 
  pull_request:
    branches: 
      - main
    types:
      - opened
      - synchronize
    paths:
      - ".github/*"
      - "scripts/*"
      - "tests/*"

jobs:
  testpipeline:
    name: Test Pipeline Check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Install node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "16.13.1"

      - name: Install ESLint, PMD, and other dependencies
        run: npm install --save-exact

      - name: Test pipeline
        run: ./scripts/testpipeline.sh

